service: backend

frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 30
  
package:
  individually: true

functions:
  hello:
    handler: packages/handlers/src/aws/AwsHello.awsHelloHandler
    events:
      - http:
          path: /
          method: get
