service: backend

frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 30
  

functions:
  createGreeting:
    handler: ../node/packages/handlers/src/Hello.handler
    events:
      - http:
          path: /
          method: get

custom:
  webpack:
    includeModules:
      packagePath: '../node/packages/handlers/package.json'
